import React from "react";
import { useTranslation } from "react-i18next";

interface ExecutiveReportPrintViewProps {
  caseData: any;
  execSummaryData: any;
  graphData: any;
  timelineData: any;
  permissions: string[];
  activities: string[];
  services: string[];
  mitreTags: { id: string; name: string }[];
  iocs: { type: string; value: string; severity: string }[];
  threatNarrative: any;
  citizenImpact: any;
  langCode?: string;
  regionalAdvisory?: any;
}

// ─── Design tokens ────────────────────────────────────────────────────────────
const ACCENT    = "#0f172a";   // near-black headings
const RED       = "#b91c1c";   // critical
const ORANGE    = "#c2410c";   // high
const AMBER     = "#92400e";   // medium
const GREEN     = "#166534";   // low/safe
const BRAND     = "#0e7490";   // BeaconTrap cyan (print-safe)
const BRAND_BG  = "#ecfeff";
const STRIPE    = "#f8fafc";   // table alternating row
const BORDER    = "#cbd5e1";
const PAGE_FONT = "Arial, Helvetica, sans-serif";
const TOTAL_PAGES = 15;

// ─── Helpers ──────────────────────────────────────────────────────────────────
function fmt(date: any) {
  if (!date) return "N/A";
  const d = new Date(date);
  return isNaN(d.getTime()) ? "N/A" : d.toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" });
}

function riskMeta(score: number) {
  if (score >= 80) return { label: "CRITICAL", color: RED,    bg: "#fef2f2", border: "#fca5a5" };
  if (score >= 60) return { label: "HIGH",     color: ORANGE, bg: "#fff7ed", border: "#fdba74" };
  if (score >= 40) return { label: "MEDIUM",   color: AMBER,  bg: "#fffbeb", border: "#fcd34d" };
  return             { label: "LOW",      color: GREEN,  bg: "#f0fdf4", border: "#86efac" };
}

function severityColor(s: string) {
  const l = s?.toLowerCase();
  if (l === "critical") return RED;
  if (l === "high")     return ORANGE;
  if (l === "medium")   return AMBER;
  return GREEN;
}

// ─── Shared sub-components ────────────────────────────────────────────────────
function PageHeader({ pageNum, section }: { pageNum: number; section: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center",
      borderBottom: `3px solid ${ACCENT}`, paddingBottom: 8, marginBottom: 28,
      fontFamily: PAGE_FONT }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <span style={{ background: ACCENT, color: "#fff", padding: "2px 10px",
          fontSize: 9, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase" }}>
          BeaconTrap Intelligence
        </span>
        <span style={{ fontSize: 9, fontWeight: 700, color: BRAND, letterSpacing: 2, textTransform: "uppercase" }}>
          {section}
        </span>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
        <span style={{ fontSize: 9, color: "#64748b", fontFamily: "monospace" }}>
          Page {pageNum} of {TOTAL_PAGES}
        </span>
        <span style={{ background: RED, color: "#fff", padding: "2px 8px",
          fontSize: 9, fontWeight: 700, letterSpacing: 2 }}>
          CONFIDENTIAL
        </span>
      </div>
    </div>
  );
}

function PageFooter({ caseId }: { caseId: string }) {
  return (
    <div style={{ marginTop: "auto", paddingTop: 16, borderTop: `1px solid ${BORDER}`,
      display: "flex", justifyContent: "space-between", alignItems: "center",
      fontFamily: PAGE_FONT, fontSize: 8, color: "#94a3b8" }}>
      <span>Generated by BeaconTrap AI Intelligence Platform · Case: {caseId}</span>
      <span>© BeaconTrap · For Authorized Personnel Only</span>
    </div>
  );
}

function SectionTitle({ num, title }: { num: string; title: string }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{ fontSize: 10, fontWeight: 700, color: BRAND, letterSpacing: 3,
        textTransform: "uppercase", fontFamily: PAGE_FONT, marginBottom: 4 }}>
        Section {num}
      </div>
      <h2 style={{ fontSize: 22, fontWeight: 800, color: ACCENT, margin: 0,
        fontFamily: PAGE_FONT, textTransform: "uppercase", letterSpacing: 1,
        borderLeft: `5px solid ${BRAND}`, paddingLeft: 14 }}>
        {title}
      </h2>
    </div>
  );
}

function CalloutBox({ title, children, color = BRAND }: { title: string; children: React.ReactNode; color?: string }) {
  return (
    <div style={{ background: BRAND_BG, border: `1px solid ${BORDER}`,
      borderLeft: `5px solid ${color}`, padding: "14px 18px", marginBottom: 16,
      fontFamily: PAGE_FONT }}>
      <div style={{ fontSize: 9, fontWeight: 800, color, textTransform: "uppercase",
        letterSpacing: 2, marginBottom: 6 }}>{title}</div>
      <div style={{ fontSize: 11, color: "#1e293b", lineHeight: 1.6 }}>{children}</div>
    </div>
  );
}

function SeverityBadge({ label }: { label: string }) {
  const rm = riskMeta(label === "CRITICAL" ? 90 : label === "HIGH" ? 70 : label === "MEDIUM" ? 50 : 20);
  return (
    <span style={{ display: "inline-block", background: rm.bg, color: rm.color,
      border: `1px solid ${rm.border}`, padding: "2px 10px", fontWeight: 800,
      fontSize: 9, letterSpacing: 2, textTransform: "uppercase",
      fontFamily: PAGE_FONT }}>
      {label}
    </span>
  );
}

function Table({ headers, rows, pageBreakInside = "avoid" }: {
  headers: string[];
  rows: (string | React.ReactNode)[][];
  pageBreakInside?: string;
}) {
  return (
    <table style={{ width: "100%", borderCollapse: "collapse", fontFamily: PAGE_FONT,
      fontSize: 10, marginBottom: 20, pageBreakInside: pageBreakInside as any }}>
      <thead>
        <tr style={{ background: ACCENT }}>
          {headers.map((h, i) => (
            <th key={i} style={{ padding: "8px 12px", textAlign: "left", color: "#fff",
              fontSize: 9, fontWeight: 700, letterSpacing: 1.5,
              textTransform: "uppercase", borderRight: "1px solid #334155" }}>
              {h}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, ri) => (
          <tr key={ri} style={{ background: ri % 2 === 0 ? "#fff" : STRIPE }}>
            {row.map((cell, ci) => (
              <td key={ci} style={{ padding: "7px 12px", borderBottom: `1px solid ${BORDER}`,
                borderRight: `1px solid ${BORDER}`, verticalAlign: "top" }}>
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function ScoreBar({ value, max = 100, color = BRAND }: { value: number; max?: number; color?: string }) {
  const pct = Math.min(100, (value / max) * 100);
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
      <div style={{ flex: 1, height: 8, background: "#e2e8f0", borderRadius: 4, overflow: "hidden" }}>
        <div style={{ width: `${pct}%`, height: "100%", background: color, borderRadius: 4 }} />
      </div>
      <span style={{ fontSize: 9, fontWeight: 700, color, width: 32, textAlign: "right" }}>{value}</span>
    </div>
  );
}

// ─── Page wrapper ─────────────────────────────────────────────────────────────
function Page({ children, pageBreakAfter = true }: { children: React.ReactNode; pageBreakAfter?: boolean }) {
  return (
    <div
      className={`print-page${pageBreakAfter ? "" : " print-page-last"}`}
      style={{
        pageBreakAfter: pageBreakAfter ? "always" : "auto",
        breakAfter: pageBreakAfter ? "page" : "auto",
        padding: "36px 48px",
        display: "flex",
        flexDirection: "column",
        background: "#fff",
        fontFamily: PAGE_FONT,
        position: "relative",
        boxSizing: "border-box",
      }}
    >
      {children}
    </div>
  );
}

// ─── Main export ──────────────────────────────────────────────────────────────
export default function ExecutiveReportPrintView({
  caseData, execSummaryData, graphData, timelineData,
  permissions, activities, services, mitreTags, iocs,
  threatNarrative, citizenImpact,
  langCode = "en", regionalAdvisory,
}: ExecutiveReportPrintViewProps) {
  const { t } = useTranslation();

  const rm   = riskMeta(caseData.riskScore);
  const cid  = caseData.id;
  const date = fmt(caseData.createdAt);

  // Derived
  const criticalIocs    = iocs.filter(i => i.severity?.toLowerCase() === "critical");
  const highIocs        = iocs.filter(i => i.severity?.toLowerCase() === "high");
  const ipIocs          = iocs.filter(i => i.type?.toLowerCase() === "ip" || i.type === "IP");
  const domainIocs      = iocs.filter(i => i.type?.toLowerCase() === "domain" || i.type === "Domain");
  const hashIocs        = iocs.filter(i => i.type?.toLowerCase().includes("hash"));
  const highRiskPerms   = permissions.filter(p =>
    ["RECEIVE_SMS","READ_SMS","SEND_SMS","SYSTEM_ALERT_WINDOW","BIND_ACCESSIBILITY_SERVICE",
     "PROCESS_OUTGOING_CALLS","RECORD_AUDIO","CAMERA","READ_CONTACTS","ACCESS_FINE_LOCATION"]
    .some(d => p.toUpperCase().includes(d))
  );

  const scoreBreakdown = [
    { name: "Permission Risk Weight",       score: caseData.permissionScore, max: 40, color: RED    },
    { name: "IOC Footprint Score",           score: caseData.iocScore,        max: 20, color: ORANGE },
    { name: "Keyword Mimicry Score",         score: caseData.keywordScore,    max: 20, color: AMBER  },
    { name: "AI Heuristic Classifier",      score: caseData.aiConfidence,    max: 20, color: BRAND  },
  ];

  return (
    <div
      className="print-report-root hidden print:block"
      style={{ background: "#fff", fontFamily: PAGE_FONT }}
      aria-hidden="true"
    >

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 1: COVER                                                          */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        {/* Top red bar */}
        <div style={{ background: ACCENT, height: 8, margin: "-36px -48px 0", width: "calc(100% + 96px)" }} />
        <div style={{ background: BRAND, height: 3, margin: "0 -48px 0", width: "calc(100% + 96px)", marginBottom: 60 }} />

        {/* Watermark-style background text */}
        <div style={{ position: "absolute", top: "38%", left: "50%", transform: "translate(-50%,-50%) rotate(-30deg)",
          fontSize: 96, fontWeight: 900, color: "rgba(15,23,42,0.03)", letterSpacing: 8,
          whiteSpace: "nowrap", userSelect: "none", pointerEvents: "none" }}>
          CONFIDENTIAL
        </div>

        {/* Logo block */}
        <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 48 }}>
          {/* Shield icon SVG */}
          <svg width="56" height="56" viewBox="0 0 24 24" fill="none" stroke={BRAND} strokeWidth="1.5">
            <path d="M12 2L3 7v5c0 5 3.5 9.74 9 11 5.5-1.26 9-6 9-11V7L12 2z" />
            <path d="M9 12l2 2 4-4" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <div>
            <div style={{ fontSize: 36, fontWeight: 900, color: ACCENT, letterSpacing: -1 }}>BeaconTrap</div>
            <div style={{ fontSize: 11, fontWeight: 600, color: BRAND, letterSpacing: 4, textTransform: "uppercase" }}>
              Cyber Threat Intelligence Platform
            </div>
          </div>
        </div>

        {/* Report title */}
        <div style={{ borderTop: `3px solid ${ACCENT}`, borderBottom: `1px solid ${BORDER}`,
          padding: "24px 0", marginBottom: 48 }}>
          <div style={{ fontSize: 9, fontWeight: 700, color: BRAND, letterSpacing: 4,
            textTransform: "uppercase", marginBottom: 8 }}>
            Intelligence Dossier · Mobile Threat Analysis
          </div>
          <h1 style={{ fontSize: 32, fontWeight: 900, color: ACCENT, margin: 0, lineHeight: 1.1 }}>
            Cyber Threat Intelligence
          </h1>
          <h1 style={{ fontSize: 32, fontWeight: 900, color: RED, margin: 0, lineHeight: 1.1 }}>
            Investigation Report
          </h1>
          <div style={{ fontSize: 13, color: "#64748b", marginTop: 12, fontStyle: "italic" }}>
            Android Binary Static Heuristic + AI Behavioral Analysis
          </div>
        </div>

        {/* Case metadata grid */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 48 }}>
          {[
            { label: "Case Reference", value: cid, mono: true },
            { label: "Analysis Date",  value: date },
            { label: "Target Binary",  value: caseData.fileName, mono: true },
            { label: "Package Name",   value: caseData.packageName || "N/A", mono: true },
            { label: "SHA-256 Hash",   value: caseData.sha256, mono: true, span: true },
          ].map((f, i) => (
            <div key={i} style={{ gridColumn: (f as any).span ? "1 / -1" : undefined,
              padding: "12px 16px", background: STRIPE, border: `1px solid ${BORDER}` }}>
              <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", letterSpacing: 2,
                textTransform: "uppercase", marginBottom: 4 }}>{f.label}</div>
              <div style={{ fontSize: f.mono ? 10 : 12, fontFamily: f.mono ? "Courier New, monospace" : PAGE_FONT,
                fontWeight: 600, color: ACCENT, wordBreak: "break-all" }}>{f.value}</div>
            </div>
          ))}
        </div>

        {/* Risk score callout */}
          <div style={{ background: rm.bg, border: `2px solid ${rm.border}`, padding: "20px 24px",
            display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 48 }}>
            <div>
              <div style={{ fontSize: 9, fontWeight: 700, color: rm.color, letterSpacing: 3,
                textTransform: "uppercase", marginBottom: 4 }}>{t('composite_risk_score')}</div>
              <div style={{ fontSize: 48, fontWeight: 900, color: rm.color, lineHeight: 1 }}>
                {caseData.riskScore}
                <span style={{ fontSize: 16, fontWeight: 400, color: "#94a3b8" }}> / 100</span>
              </div>
            </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 24, fontWeight: 900, color: rm.color, letterSpacing: 2 }}>{rm.label}</div>
            <div style={{ fontSize: 13, color: "#64748b", marginTop: 4 }}>
              {caseData.threatFamily || "Unclassified"}
            </div>
            <div style={{ fontSize: 11, color: "#94a3b8" }}>
              Confidence: {caseData.aiConfidence || caseData.threatConfidence || 90}%
            </div>
          </div>
        </div>

        {/* Classification footer */}
        <div style={{ marginTop: "auto", borderTop: `3px double ${ACCENT}`, paddingTop: 16,
          display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ fontSize: 9, color: "#64748b" }}>
            Distribution: Authorized Cybersecurity Personnel Only
          </div>
          <div style={{ background: RED, color: "#fff", padding: "6px 20px",
            fontSize: 11, fontWeight: 900, letterSpacing: 3 }}>
            CLASSIFICATION: CONFIDENTIAL
          </div>
        </div>
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 2: EXECUTIVE SUMMARY                                              */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={2} section={t('executive_summary')} />
        <SectionTitle num="1" title={t('executive_summary')} />

        {execSummaryData ? (<>
          <CalloutBox title="Strategic Risk Assessment" color={rm.color}>
            {execSummaryData.executiveRiskSummary}
          </CalloutBox>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, marginBottom: 20 }}>
            {[
              { label: "Priority Level",      value: execSummaryData.priorityLevel,     color: rm.color },
              { label: "Estimated Exposure",   value: execSummaryData.estimatedExposure, color: ORANGE   },
              { label: "AI Confidence",        value: `${caseData.aiConfidence || 90}%`, color: BRAND    },
            ].map((kpi, i) => (
              <div key={i} style={{ padding: "16px", background: STRIPE,
                border: `1px solid ${BORDER}`, borderTop: `3px solid ${kpi.color}` }}>
                <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", letterSpacing: 2,
                  textTransform: "uppercase", marginBottom: 6 }}>{kpi.label}</div>
                <div style={{ fontSize: 18, fontWeight: 900, color: kpi.color }}>{kpi.value}</div>
              </div>
            ))}
          </div>

          <CalloutBox title="Business Impact Assessment" color={ORANGE}>
            {execSummaryData.businessImpact}
          </CalloutBox>

          {langCode !== "en" && regionalAdvisory && regionalAdvisory[langCode] && (
            <CalloutBox title="Regional Citizen Advisory (Translated)" color={BRAND}>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 8, color: ACCENT }}>
                {regionalAdvisory[langCode].summary}
              </div>
              <div style={{ fontSize: 11, color: RED, fontWeight: 500 }}>
                {regionalAdvisory[langCode].advisory}
              </div>
            </CalloutBox>
          )}

          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              Key Findings
            </div>
            {[
              `Threat Family Identified: ${caseData.threatFamily || "Unclassified"}`,
              `Composite Risk Score: ${caseData.riskScore}/100 (${rm.label})`,
              `Dangerous Permissions Detected: ${highRiskPerms.length} of ${permissions.length} total`,
              `MITRE ATT&CK Techniques Mapped: ${mitreTags.length}`,
              `Network Indicators of Compromise: ${iocs.length} (${criticalIocs.length} Critical)`,
              `Blockchain Evidence: ${caseData.blockchainTxHash ? "Recorded" : "Pending"}`,
            ].map((finding, i) => (
              <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 10, padding: "8px 0",
                borderBottom: `1px solid ${BORDER}` }}>
                <span style={{ fontSize: 10, color: BRAND, fontWeight: 700, marginTop: 1 }}>▶</span>
                <span style={{ fontSize: 11, color: "#334155" }}>{finding}</span>
              </div>
            ))}
          </div>
        </>) : (
          <p style={{ color: "#64748b", fontStyle: "italic" }}>Executive summary not available.</p>
        )}
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 3: TECHNICAL MALWARE ANALYSIS                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={3} section={t('technical_analysis')} />
        <SectionTitle num="2" title={t('technical_analysis')} />

        {/* Primary classification card */}
        <div style={{ background: rm.bg, border: `2px solid ${rm.border}`, padding: 20, marginBottom: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <div style={{ fontSize: 9, fontWeight: 700, color: rm.color, letterSpacing: 2,
                textTransform: "uppercase", marginBottom: 4 }}>Primary Classification</div>
              <div style={{ fontSize: 28, fontWeight: 900, color: rm.color }}>
                {caseData.threatFamily || "UNCLASSIFIED THREAT"}
              </div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 4 }}>
                {caseData.malwareType || "Android Malware"}
              </div>
            </div>
            <div style={{ textAlign: "right" }}>
              <SeverityBadge label={rm.label} />
              <div style={{ fontSize: 32, fontWeight: 900, color: rm.color, marginTop: 8 }}>
                {caseData.riskScore}/100
              </div>
            </div>
          </div>
        </div>

        {/* Risk component breakdown */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 12, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            Risk Score Decomposition
          </div>
          {scoreBreakdown.map((item, i) => (
            <div key={i} style={{ marginBottom: 12 }}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
                <span style={{ fontSize: 10, fontWeight: 600, color: ACCENT }}>{item.name}</span>
                <span style={{ fontSize: 10, fontWeight: 700, color: item.color }}>
                  {item.score || 0}/{item.max}
                </span>
              </div>
              <ScoreBar value={Math.round(((item.score || 0) / item.max) * 100)} color={item.color} />
            </div>
          ))}
        </div>

        {/* Classification matrix table */}
        <Table
          headers={["Attribute", "Value", "Severity"]}
          rows={[
            ["Threat Family",   caseData.threatFamily || "Unknown",      <SeverityBadge label={rm.label} />],
            ["Malware Type",    caseData.malwareType || "Android Malware", ""],
            ["Risk Score",      `${caseData.riskScore}/100`,             <SeverityBadge label={rm.label} />],
            ["AI Confidence",   `${caseData.aiConfidence || 90}%`,       "HIGH"],
            ["Permissions",     `${permissions.length} declared / ${highRiskPerms.length} high-risk`, highRiskPerms.length > 5 ? <SeverityBadge label="CRITICAL" /> : <SeverityBadge label="HIGH" />],
            ["IOC Count",       `${iocs.length} total / ${criticalIocs.length} critical`, criticalIocs.length > 0 ? <SeverityBadge label="CRITICAL" /> : ""],
            ["MITRE Techniques",`${mitreTags.length} mapped`,            mitreTags.length > 5 ? <SeverityBadge label="HIGH" /> : <SeverityBadge label="MEDIUM" />],
            ["Analysis Mode",   caseData.analysisMode,                   ""],
          ]}
        />

        <CalloutBox title="Classification Rationale" color={rm.color}>
          This sample has been classified as <strong>{rm.label}</strong> based on its composite risk
          score of <strong>{caseData.riskScore}/100</strong>. The primary risk drivers are
          {highRiskPerms.length > 0 && ` excessive permission abuse (${highRiskPerms.length} dangerous permissions),`}
          {mitreTags.length > 0 && ` mapping to ${mitreTags.length} MITRE ATT&CK techniques,`}
          {criticalIocs.length > 0 && ` and ${criticalIocs.length} critical network indicators of compromise.`}
          {" "}Immediate escalation is recommended.
        </CalloutBox>
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 4: TECHNICAL MALWARE ANALYSIS                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={4} section="Technical Malware Analysis" />
        <SectionTitle num="3" title="Technical Malware Analysis" />

        <CalloutBox title="Behavioral Threat Narrative" color={BRAND}>
          {threatNarrative?.behavior || "Detailed behavioral analysis not available for this sample."}
        </CalloutBox>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 }}>
          {/* Static metadata */}
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              Binary Metadata
            </div>
            {[
              { label: "File Name",    value: caseData.fileName },
              { label: "Package",      value: caseData.packageName || "N/A" },
              { label: "Version",      value: caseData.versionCode || "N/A" },
              { label: "File Size",    value: `${((caseData.fileSize || 0) / 1024 / 1024).toFixed(2)} MB` },
              { label: "SHA-256",      value: (caseData.sha256 || "").slice(0, 32) + "..." },
            ].map((r, i) => (
              <div key={i} style={{ display: "flex", borderBottom: `1px solid ${BORDER}`,
                padding: "6px 0", fontSize: 10 }}>
                <span style={{ width: 100, fontWeight: 700, color: "#64748b", flexShrink: 0 }}>{r.label}</span>
                <span style={{ fontFamily: "Courier New, monospace", color: ACCENT, wordBreak: "break-all" }}>{r.value}</span>
              </div>
            ))}
          </div>

          {/* Threat vectors */}
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              Threat Vector Analysis
            </div>
            {[
              { label: "OTP Interception",    value: threatNarrative?.otpTheft, severity: "CRITICAL" },
              { label: "Accessibility Abuse", value: threatNarrative?.accessibilityAbuse, severity: "HIGH" },
              { label: "Credential Theft",    value: threatNarrative?.credentialTheft, severity: "HIGH" },
              { label: "Fraud Risk Profile",  value: threatNarrative?.fraudRisks, severity: "MEDIUM" },
            ].map((v, i) => (
              <div key={i} style={{ padding: "8px 0", borderBottom: `1px solid ${BORDER}`, fontSize: 10 }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 2 }}>
                  <span style={{ fontWeight: 700, color: ACCENT }}>{v.label}</span>
                  <SeverityBadge label={v.severity} />
                </div>
                <span style={{ color: "#475569" }}>{v.value || "No indicators detected"}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Permission analysis */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            Dangerous Permissions Inventory ({highRiskPerms.length} of {permissions.length})
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 }}>
            {(highRiskPerms.length > 0 ? highRiskPerms : permissions).slice(0, 16).map((p, i) => (
              <div key={i} style={{ padding: "5px 10px", background: highRiskPerms.includes(p) ? "#fef2f2" : STRIPE,
                border: `1px solid ${highRiskPerms.includes(p) ? "#fca5a5" : BORDER}`,
                fontSize: 9, fontFamily: "Courier New, monospace",
                color: highRiskPerms.includes(p) ? RED : "#334155" }}>
                {p.replace("android.permission.", "")}
              </div>
            ))}
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 8, borderBottom: `1px solid ${BORDER}`, paddingBottom: 4 }}>
              Activity Components ({activities.length})
            </div>
            {activities.slice(0, 8).map((a, i) => (
              <div key={i} style={{ fontSize: 9, fontFamily: "Courier New, monospace",
                color: "#475569", padding: "3px 0", borderBottom: `1px solid ${BORDER}` }}>
                {a.split(".").pop()}
              </div>
            ))}
          </div>
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 8, borderBottom: `1px solid ${BORDER}`, paddingBottom: 4 }}>
              Background Services ({services.length})
            </div>
            {services.slice(0, 8).map((s, i) => (
              <div key={i} style={{ fontSize: 9, fontFamily: "Courier New, monospace",
                color: "#475569", padding: "3px 0", borderBottom: `1px solid ${BORDER}` }}>
                {s.split(".").pop()}
              </div>
            ))}
          </div>
        </div>
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 5: MITRE ATT&CK MAPPING                                           */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={5} section="MITRE ATT&CK Mapping" />
        <SectionTitle num="4" title="MITRE ATT&CK Mobile Matrix Mapping" />

        <CalloutBox title="Framework Reference" color={BRAND}>
          The following techniques have been mapped against the MITRE ATT&CK® for Mobile framework (v14).
          Techniques are extracted through static heuristic analysis and AI behavioral correlation of
          the binary payload patterns, permission abuse, and string artefacts.
        </CalloutBox>

        {mitreTags.length > 0 ? (<>
          <Table
            headers={["Technique ID", "Technique Name", "Tactic Phase", "Confidence", "Severity"]}
            rows={mitreTags.map((tag, i) => {
              const tactic = tag.id.startsWith("T14") ? "Collection" :
                             tag.id.startsWith("T15") ? "Exfiltration" :
                             tag.id.startsWith("T16") ? "Impact" :
                             tag.id.startsWith("T10") ? "Initial Access" : "Execution";
              const conf = 90 - (i * 3);
              return [
                <span style={{ fontFamily: "Courier New, monospace", fontWeight: 700, color: RED, fontSize: 11 }}>{tag.id}</span>,
                <span style={{ fontWeight: 600, color: ACCENT }}>{tag.name}</span>,
                tactic,
                `${conf}%`,
                <SeverityBadge label={i < 2 ? "CRITICAL" : i < 4 ? "HIGH" : "MEDIUM"} />,
              ];
            })}
          />

          {/* Kill chain visual */}
          <div style={{ marginTop: 20 }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 14, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              ATT&CK Kill Chain Progression
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 0, flexWrap: "wrap" }}>
              {["Initial Access", "Execution", "Persistence", "Credential Access", "Collection", "C2"].map((phase, i) => (
                <React.Fragment key={i}>
                  <div style={{ background: i < 4 ? ACCENT : "#94a3b8", color: "#fff",
                    padding: "8px 12px", fontSize: 9, fontWeight: 700, textAlign: "center",
                    minWidth: 80, textTransform: "uppercase", letterSpacing: 0.5 }}>
                    {phase}
                  </div>
                  {i < 5 && (
                    <div style={{ fontSize: 14, color: i < 4 ? BRAND : "#94a3b8", padding: "0 4px" }}>▶</div>
                  )}
                </React.Fragment>
              ))}
            </div>
            <div style={{ fontSize: 9, color: "#94a3b8", marginTop: 8 }}>
              Shaded stages indicate confirmed detection. Greyed stages indicate unconfirmed.
            </div>
          </div>
        </>) : (
          <p style={{ color: "#64748b", fontStyle: "italic" }}>No MITRE ATT&CK techniques mapped for this sample.</p>
        )}
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 6: NETWORK INFRASTRUCTURE ANALYSIS                                */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={6} section="Network Infrastructure Analysis" />
        <SectionTitle num="5" title="Network Infrastructure Analysis" />

        <CalloutBox title="Infrastructure Summary" color={ORANGE}>
          Analysis has identified {iocs.length} network indicators of compromise, including {ipIocs.length} IP
          addresses and {domainIocs.length} malicious domains. {criticalIocs.length > 0 && `${criticalIocs.length} indicators
          are rated CRITICAL and indicate active command-and-control (C2) infrastructure.`}
        </CalloutBox>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: 12, marginBottom: 20 }}>
          {[
            { label: "Total IOCs",    value: iocs.length,          color: ACCENT },
            { label: "Critical",      value: criticalIocs.length,  color: RED    },
            { label: "IP Addresses",  value: ipIocs.length,        color: ORANGE },
            { label: "Domains",       value: domainIocs.length,    color: BRAND  },
          ].map((kpi, i) => (
            <div key={i} style={{ padding: 14, background: STRIPE,
              border: `1px solid ${BORDER}`, borderTop: `3px solid ${kpi.color}`, textAlign: "center" }}>
              <div style={{ fontSize: 28, fontWeight: 900, color: kpi.color }}>{kpi.value}</div>
              <div style={{ fontSize: 9, fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: 1 }}>
                {kpi.label}
              </div>
            </div>
          ))}
        </div>

        {ipIocs.length > 0 && (<>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            C2 IP Address Registry
          </div>
          <Table
            headers={["IP Address", "Threat Role", "Severity", "Classification"]}
            rows={ipIocs.map(ioc => [
              <span style={{ fontFamily: "Courier New, monospace", fontWeight: 700 }}>{ioc.value}</span>,
              "Command & Control",
              <SeverityBadge label={ioc.severity?.toUpperCase() === "CRITICAL" ? "CRITICAL" : "HIGH"} />,
              "Bulletproof Infrastructure",
            ])}
          />
        </>)}

        {domainIocs.length > 0 && (<>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6, marginTop: 16 }}>
            Malicious Domain Registry
          </div>
          <Table
            headers={["Domain", "Threat Role", "Severity", "Category"]}
            rows={domainIocs.map(ioc => [
              <span style={{ fontFamily: "Courier New, monospace", fontWeight: 700, color: RED }}>{ioc.value}</span>,
              "Phishing / C2 Relay",
              <SeverityBadge label={ioc.severity?.toUpperCase() === "CRITICAL" ? "CRITICAL" : "HIGH"} />,
              "Typosquatting / Fraud Gateway",
            ])}
          />
        </>)}

        <CalloutBox title="Banking Impact — Network Vector" color={RED}>
          {threatNarrative?.bankingImpact || "Network infrastructure assessment indicates potential for financial fraud facilitation."}
        </CalloutBox>
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 7: INDICATORS OF COMPROMISE                                       */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={7} section="Indicators of Compromise" />
        <SectionTitle num="6" title="Indicators of Compromise (IOCs)" />

        <CalloutBox title="IOC Extraction Methodology" color={BRAND}>
          IOCs were extracted through static string analysis, permission profiling, and AI-assisted
          behavioral pattern matching. All indicators below should be added to threat intelligence
          platforms, SIEM blocklists, and firewall deny-rules immediately.
        </CalloutBox>

        {iocs.length > 0 ? (
          <Table
            pageBreakInside="auto"
            headers={["#", "IOC Type", "Indicator Value", "Severity", "Action Required"]}
            rows={iocs.map((ioc, i) => [
              <span style={{ color: "#94a3b8", fontSize: 9 }}>{i + 1}</span>,
              <span style={{ fontWeight: 700, color: BRAND, textTransform: "uppercase",
                fontSize: 9, letterSpacing: 1 }}>{ioc.type}</span>,
              <span style={{ fontFamily: "Courier New, monospace", fontSize: 9,
                color: ioc.severity?.toLowerCase() === "critical" ? RED : ACCENT,
                wordBreak: "break-all" }}>{ioc.value}</span>,
              <SeverityBadge label={ioc.severity?.toUpperCase() === "CRITICAL" ? "CRITICAL" :
                              ioc.severity?.toUpperCase() === "HIGH" ? "HIGH" : "MEDIUM"} />,
              ioc.severity?.toLowerCase() === "critical" ? "Block immediately" : "Monitor & alert",
            ])}
          />
        ) : (
          <p style={{ color: "#64748b", fontStyle: "italic" }}>No network indicators of compromise identified.</p>
        )}

        {/* Hash IOC section */}
        <div style={{ marginTop: 16 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            Binary Hash Fingerprints
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "120px 1fr", gap: 0, fontSize: 10 }}>
            {[
              { label: "SHA-256", value: caseData.sha256 },
            ].map((h, i) => (
              <React.Fragment key={i}>
                <div style={{ padding: "8px 12px", background: ACCENT, color: "#fff",
                  fontWeight: 700, fontSize: 9, letterSpacing: 1, display: "flex", alignItems: "center" }}>
                  {h.label}
                </div>
                <div style={{ padding: "8px 12px", background: STRIPE, border: `1px solid ${BORDER}`,
                  fontFamily: "Courier New, monospace", fontSize: 9, wordBreak: "break-all" }}>
                  {h.value || "N/A"}
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 8: RISK ATTRIBUTION BREAKDOWN                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={8} section="Risk Attribution Breakdown" />
        <SectionTitle num="7" title="Risk Attribution Breakdown" />

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 24 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 14, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              Composite Score Breakdown
            </div>
            {scoreBreakdown.map((item, i) => (
              <div key={i} style={{ marginBottom: 16, padding: "12px", background: STRIPE,
                border: `1px solid ${BORDER}`, borderLeft: `4px solid ${item.color}` }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
                  <span style={{ fontSize: 10, fontWeight: 700, color: ACCENT }}>{item.name}</span>
                  <span style={{ fontSize: 12, fontWeight: 900, color: item.color }}>
                    {item.score || 0}/{item.max}
                  </span>
                </div>
                <ScoreBar value={Math.round(((item.score || 0) / item.max) * 100)} color={item.color} />
              </div>
            ))}
          </div>

          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
              letterSpacing: 1, marginBottom: 14, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
              Attribution Signals
            </div>
            {[
              { label: "Threat Actor TTPs",   value: `${mitreTags.length} techniques matched`,    severity: "CRITICAL" },
              { label: "C2 Infrastructure",   value: `${ipIocs.length} IPs / ${domainIocs.length} domains`, severity: "HIGH" },
              { label: "Code Similarity",     value: `${caseData.aiConfidence || 85}% match to known families`, severity: "HIGH" },
              { label: "Permission Overlap",  value: `${highRiskPerms.length} dangerous APIs`, severity: "MEDIUM" },
              { label: "Keyword Signatures",  value: `${caseData.keywordScore || 0}/20 score`, severity: "MEDIUM" },
            ].map((sig, i) => (
              <div key={i} style={{ padding: "10px 12px", background: STRIPE,
                border: `1px solid ${BORDER}`, marginBottom: 8,
                display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div>
                  <div style={{ fontSize: 10, fontWeight: 700, color: ACCENT }}>{sig.label}</div>
                  <div style={{ fontSize: 9, color: "#64748b", marginTop: 2 }}>{sig.value}</div>
                </div>
                <SeverityBadge label={sig.severity} />
              </div>
            ))}
          </div>
        </div>

        <CalloutBox title="Risk Attribution Summary" color={rm.color}>
          Based on multi-factor analysis, this sample scores <strong>{caseData.riskScore}/100</strong> on
          the BeaconTrap composite risk scale. The dominant risk contributors are permission-based API
          abuse ({caseData.permissionScore || 0}/40) and AI heuristic classification ({caseData.aiConfidence || 90}% confidence).
          Attribution confidence for the identified threat family is <strong>{caseData.threatConfidence || 90}%</strong>.
        </CalloutBox>
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 9: CAMPAIGN DNA RELATIONSHIPS                                      */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={9} section="Campaign DNA Relationships" />
        <SectionTitle num="8" title="Campaign DNA & Threat Relationships" />

        <CalloutBox title="Campaign Correlation Overview" color={BRAND}>
          The following graph outlines the threat infrastructure relationships identified through
          IOC correlation, shared C2 infrastructure analysis, and malware family signature matching.
        </CalloutBox>

        {/* Textual graph representation */}
        <div style={{ border: `2px solid ${BORDER}`, padding: 20, background: "#f8fafc", marginBottom: 20 }}>
          <div style={{ textAlign: "center", marginBottom: 20 }}>
            <div style={{ display: "inline-block", background: RED, color: "#fff",
              padding: "10px 20px", fontWeight: 900, fontSize: 13, letterSpacing: 1 }}>
              ◉ {caseData.fileName}
            </div>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
            {[
              { title: "Threat Family", items: [caseData.threatFamily || "Banking Trojan"], color: "#7c3aed" },
              { title: "Network IOCs",  items: [...ipIocs.map(i => i.value), ...domainIocs.map(i => i.value)].slice(0, 4), color: RED },
              { title: "MITRE Techniques", items: mitreTags.slice(0, 4).map(t => t.id), color: BRAND },
            ].map((group, gi) => (
              <div key={gi} style={{ border: `1px solid ${BORDER}`, padding: 10 }}>
                <div style={{ fontSize: 9, fontWeight: 700, color: group.color, textTransform: "uppercase",
                  letterSpacing: 1, marginBottom: 8, borderBottom: `1px solid ${BORDER}`, paddingBottom: 4 }}>
                  {group.title}
                </div>
                {group.items.map((item, ii) => (
                  <div key={ii} style={{ fontSize: 9, fontFamily: "Courier New, monospace",
                    color: ACCENT, padding: "3px 0", borderBottom: `1px solid ${BORDER}` }}>
                    → {item}
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>

        <Table
          headers={["Relationship Type", "Entity", "Confidence", "Attribution"]}
          rows={[
            ["Classified As", caseData.threatFamily || "Unknown", "97%", "AI Classification"],
            ...ipIocs.slice(0, 3).map(ioc => ["C2 Beacon", ioc.value, "94%", "Static Analysis"]),
            ...domainIocs.slice(0, 3).map(ioc => ["Resolves To", ioc.value, "91%", "DNS Correlation"]),
            ...mitreTags.slice(0, 3).map(tag => ["Uses Technique", `${tag.id} · ${tag.name}`, "88%", "Behavioral Match"]),
          ]}
        />
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 10: CITIZEN IMPACT ASSESSMENT                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={10} section="Citizen Impact Assessment" />
        <SectionTitle num="9" title="Citizen Impact Assessment" />

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, marginBottom: 20 }}>
          {[
            { label: "Affected Population", value: citizenImpact?.affectedPopulation || "High Exposure",  color: RED    },
            { label: "Target Group",        value: citizenImpact?.targetGroup || "UPI & Mobile Banking Users", color: ORANGE },
            { label: "Priority Level",      value: citizenImpact?.priority || "Immediate Action", color: rm.color },
          ].map((kpi, i) => (
            <div key={i} style={{ padding: 16, background: STRIPE,
              border: `1px solid ${BORDER}`, borderTop: `3px solid ${kpi.color}` }}>
              <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", letterSpacing: 2,
                textTransform: "uppercase", marginBottom: 6 }}>{kpi.label}</div>
              <div style={{ fontSize: 14, fontWeight: 800, color: kpi.color }}>{kpi.value}</div>
            </div>
          ))}
        </div>

        <Table
          headers={["Impact Dimension", "Assessment", "Severity"]}
          rows={[
            ["Fraud Type",           citizenImpact?.fraudType || "UPI/IMPS Financial Fraud",   <SeverityBadge label="CRITICAL" />],
            ["Affected Segment",     citizenImpact?.targetGroup || "Retail Banking Customers",  <SeverityBadge label="HIGH"     />],
            ["OTP Theft Risk",       threatNarrative?.otpTheft || "Active indicators detected", <SeverityBadge label="CRITICAL" />],
            ["Data Exfiltration",    threatNarrative?.credentialTheft || "Credential harvesting confirmed", <SeverityBadge label="HIGH" />],
            ["Accessibility Abuse",  threatNarrative?.accessibilityAbuse || "Overlay attack possible",  <SeverityBadge label="HIGH" />],
            ["Banking Impact Scope", threatNarrative?.bankingImpact || "Wide banking ecosystem exposure", <SeverityBadge label={rm.label} />],
          ]}
        />

        <CalloutBox title="RBI & CERT-In Advisory Context" color={RED}>
          Based on the observed threat behavior, this application poses significant risk to Indian
          mobile banking users. The combination of SMS interception, accessibility service abuse,
          and credential harvesting capabilities aligns with patterns associated with UPI fraud
          campaigns. Immediate advisory issuance through CERT-In and RBI Digital Banking channels
          is recommended.
        </CalloutBox>
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 11: BANK OFFICER MITIGATION PLAN                                  */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={11} section="Bank Officer Mitigation Plan" />
        <SectionTitle num="10" title="Bank Officer Mitigation Plan" />

        <CalloutBox title="Compliance & Regulatory Context" color={BRAND}>
          This section provides actionable guidance for bank compliance officers, fraud prevention
          teams, and IT security departments. Recommendations are aligned with RBI Cybersecurity
          Framework, ISO 27001, and PCI-DSS requirements.
        </CalloutBox>

        <Table
          headers={["Priority", "Action Item", "Owner", "Timeline", "Status"]}
          rows={[
            [<SeverityBadge label="CRITICAL" />, "Block identified C2 IPs at perimeter firewall", "Network Security Team", "Immediate (0-2 hrs)", "◉ Required"],
            [<SeverityBadge label="CRITICAL" />, "Add malicious domains to DNS blocklist", "IT Security", "Immediate (0-4 hrs)", "◉ Required"],
            [<SeverityBadge label="HIGH"     />, "Alert fraud monitoring system with IOC signatures", "Fraud Analytics", "Same Day", "◉ Required"],
            [<SeverityBadge label="HIGH"     />, "Issue customer advisory for suspicious app", "Digital Banking", "24 Hours", "⚠ Urgent"],
            [<SeverityBadge label="HIGH"     />, "Escalate to CERT-In via cybersecurity reporting portal", "CISO Office", "24 Hours", "⚠ Urgent"],
            [<SeverityBadge label="MEDIUM"   />, "Review recent transaction anomalies from affected users", "Fraud Ops", "48 Hours", "▷ Planned"],
            [<SeverityBadge label="MEDIUM"   />, "File regulatory incident report with RBI", "Compliance Team", "72 Hours", "▷ Planned"],
            [<SeverityBadge label="MEDIUM"   />, "Update mobile banking app security review process", "Product Security", "1 Week", "▷ Planned"],
          ]}
        />

        {execSummaryData?.recommendedActions?.length > 0 && (<>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            AI-Generated Strategic Recommendations
          </div>
          {execSummaryData.recommendedActions.map((action: string, i: number) => (
            <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 12, padding: "10px 12px",
              background: i % 2 === 0 ? STRIPE : "#fff", border: `1px solid ${BORDER}`,
              marginBottom: 4, fontSize: 10 }}>
              <span style={{ background: BRAND, color: "#fff", width: 20, height: 20,
                display: "flex", alignItems: "center", justifyContent: "center",
                fontWeight: 900, fontSize: 9, flexShrink: 0 }}>{i + 1}</span>
              <span style={{ color: "#1e293b", lineHeight: 1.5 }}>{action}</span>
            </div>
          ))}
        </>)}
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 12: INCIDENT TIMELINE                                              */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={12} section="Incident Timeline" />
        <SectionTitle num="11" title="Investigation Timeline" />

        <CalloutBox title="Timeline Methodology" color={BRAND}>
          The following chronological reconstruction documents key events in the investigation
          pipeline. Timestamps are recorded in IST (UTC+5:30).
        </CalloutBox>

        {timelineData && timelineData.length > 0 ? (
          <div>
            {timelineData.map((event: any, i: number) => (
              <div key={i} style={{ display: "flex", gap: 16, marginBottom: 14,
                pageBreakInside: "avoid" }}>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", flexShrink: 0 }}>
                  <div style={{ width: 12, height: 12, borderRadius: "50%",
                    background: i === 0 ? RED : i < 4 ? BRAND : GREEN, marginTop: 2 }} />
                  {i < timelineData.length - 1 && (
                    <div style={{ width: 2, flex: 1, background: BORDER, marginTop: 4 }} />
                  )}
                </div>
                <div style={{ flex: 1, padding: "0 0 14px 0", borderBottom: `1px solid ${BORDER}` }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
                    <span style={{ fontWeight: 700, fontSize: 11, color: ACCENT }}>{event.event}</span>
                    <span style={{ fontSize: 9, fontFamily: "Courier New, monospace",
                      color: "#64748b" }}>{fmt(event.timestamp)}</span>
                  </div>
                  <p style={{ fontSize: 10, color: "#475569", margin: 0, lineHeight: 1.5 }}>
                    {event.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div>
            {[
              { phase: "APK Received", desc: "Binary submitted to BeaconTrap analysis pipeline. SHA-256 fingerprint computed and case file opened.", time: date },
              { phase: "Static Analysis", desc: "DEX bytecode parsed. Android manifest extracted. Permission profile compiled.", time: "" },
              { phase: "IOC Extraction", desc: "String artefacts scanned. Network indicators identified and correlated against threat intelligence feeds.", time: "" },
              { phase: "MITRE Mapping", desc: "Behavioral signatures cross-referenced against MITRE ATT&CK Mobile v14. Techniques mapped.", time: "" },
              { phase: "AI Correlation", desc: `Gemini AI heuristic classification completed. Threat family identified as ${caseData.threatFamily || "Unknown"} with ${caseData.aiConfidence || 90}% confidence.`, time: "" },
              { phase: "Risk Assessment", desc: `Composite risk score calculated: ${caseData.riskScore}/100 (${rm.label}).`, time: "" },
              { phase: "Report Generation", desc: "Multi-persona intelligence reports generated for Security Analyst, Bank Officer, and Executive audiences.", time: "" },
              { phase: "Blockchain Verification", desc: `Evidence integrity recorded on Sepolia ledger. TX: ${caseData.blockchainTxHash || "Pending"}`, time: "" },
            ].map((ev, i) => (
              <div key={i} style={{ display: "flex", gap: 16, marginBottom: 14 }}>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", flexShrink: 0 }}>
                  <div style={{ width: 12, height: 12, borderRadius: "50%",
                    background: i === 0 ? RED : i < 5 ? BRAND : GREEN }} />
                  {i < 7 && <div style={{ width: 2, height: 20, background: BORDER, marginTop: 2 }} />}
                </div>
                <div style={{ flex: 1, paddingBottom: 10, borderBottom: `1px solid ${BORDER}` }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <span style={{ fontWeight: 700, fontSize: 11, color: ACCENT }}>Stage {i+1}: {ev.phase}</span>
                    {ev.time && <span style={{ fontSize: 9, color: "#94a3b8", fontFamily: "Courier New, monospace" }}>{ev.time}</span>}
                  </div>
                  <p style={{ fontSize: 10, color: "#475569", margin: "4px 0 0", lineHeight: 1.5 }}>{ev.desc}</p>
                </div>
              </div>
            ))}
          </div>
        )}
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 13: STRATEGIC RECOMMENDATIONS                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={13} section="Strategic Recommendations" />
        <SectionTitle num="12" title="Strategic Recommendations" />

        <CalloutBox title="Executive Directive" color={RED}>
          The threat represented by this sample requires immediate multi-team response. The following
          recommendations are stratified by urgency and function. Board-level awareness is advised
          given the potential for large-scale customer financial exposure.
        </CalloutBox>

        {[
          { tier: "Tier 1 — Immediate (0–24 hrs)", color: RED, items: [
            "Block all identified C2 IPs and domains at network perimeter",
            "Activate fraud monitoring playbook and increase alert sensitivity for UPI transactions",
            "Notify CERT-In and Reserve Bank of India Cybersecurity Cell",
            "Issue internal security advisory to branch staff and digital banking teams",
          ]},
          { tier: "Tier 2 — Short-Term (1–7 days)", color: ORANGE, items: [
            "Conduct threat hunting sweep for similar APK signatures across managed devices",
            "Review Play Store / third-party store listings for the identified package name",
            "Brief senior management and Risk Committee with this intelligence report",
            "Patch mobile banking application to add APK signature verification",
          ]},
          { tier: "Tier 3 — Strategic (1–4 weeks)", color: BRAND, items: [
            "Commission third-party penetration test of mobile banking application",
            "Implement Device Intelligence SDK to detect sideloaded applications",
            "Develop customer awareness campaign targeting UPI fraud patterns",
            "Review and update Incident Response Plan to include mobile threat scenarios",
          ]},
        ].map((section, si) => (
          <div key={si} style={{ marginBottom: 20 }}>
            <div style={{ background: section.color, color: "#fff", padding: "8px 16px",
              fontSize: 11, fontWeight: 800, marginBottom: 0, letterSpacing: 0.5 }}>
              {section.tier}
            </div>
            {section.items.map((item, i) => (
              <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 12,
                padding: "10px 16px", background: i % 2 === 0 ? STRIPE : "#fff",
                border: `1px solid ${BORDER}`, borderTop: "none", fontSize: 10 }}>
                <span style={{ color: section.color, fontWeight: 700, flexShrink: 0 }}>→</span>
                <span style={{ color: "#1e293b", lineHeight: 1.5 }}>{item}</span>
              </div>
            ))}
          </div>
        ))}
        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 14: EVIDENCE INTEGRITY                                            */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page>
        <PageHeader pageNum={14} section="Evidence Integrity" />
        <SectionTitle num="13" title="Evidence Integrity & Blockchain Verification" />

        <CalloutBox title="Chain of Custody Statement" color={GREEN}>
          All digital evidence in this investigation has been cryptographically hashed and recorded
          on an immutable blockchain ledger. This guarantees tamper-proof integrity of findings and
          ensures regulatory admissibility of evidence in legal proceedings.
        </CalloutBox>

        {/* Blockchain details */}
        <div style={{ background: "#f0fdf4", border: `2px solid #86efac`, padding: 24, marginBottom: 20 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke={GREEN} strokeWidth="2">
              <path d="M12 2L3 7v5c0 5 3.5 9.74 9 11 5.5-1.26 9-6 9-11V7L12 2z" />
              <path d="M9 12l2 2 4-4" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            <span style={{ fontWeight: 800, color: GREEN, fontSize: 14, textTransform: "uppercase",
              letterSpacing: 2 }}>Blockchain-Verified Evidence Record</span>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "180px 1fr", gap: 0, fontSize: 10 }}>
            {[
              { label: "Network",             value: "Sepolia Testnet (Ethereum-compatible)" },
              { label: "Transaction Hash",    value: caseData.blockchainTxHash || "Pending — awaiting confirmation" },
              { label: "Block Number",        value: caseData.blockchainBlock ? `#${caseData.blockchainBlock}` : "N/A" },
              { label: "Ledger Timestamp",    value: fmt(caseData.blockchainTimestamp) },
              { label: "Evidence Type",       value: "SHA-256 Digest of Analysis Report" },
              { label: "Integrity Status",    value: caseData.blockchainTxHash ? "✓ VERIFIED — Tamper-proof record exists" : "⏳ PENDING — Awaiting on-chain confirmation" },
            ].map((row, i) => (
              <React.Fragment key={i}>
                <div style={{ padding: "8px 12px", background: "rgba(22,101,52,0.1)",
                  fontWeight: 700, fontSize: 9, letterSpacing: 1, color: GREEN,
                  textTransform: "uppercase", borderBottom: `1px solid #bbf7d0`,
                  display: "flex", alignItems: "center" }}>
                  {row.label}
                </div>
                <div style={{ padding: "8px 12px", borderBottom: `1px solid #bbf7d0`,
                  fontFamily: row.label.includes("Hash") || row.label.includes("Block") ? "Courier New, monospace" : PAGE_FONT,
                  fontSize: 9, color: ACCENT, wordBreak: "break-all",
                  background: i % 2 === 0 ? "#fff" : "#f0fdf4" }}>
                  {row.value}
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>

        {/* Analyst signature block */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginTop: 24 }}>
          {[
            { title: "Generated By", name: "BeaconTrap AI Engine", role: "Automated Analysis Platform" },
            { title: "Case Reference", name: cid, role: `Analysis Date: ${date}` },
          ].map((sig, i) => (
            <div key={i} style={{ border: `1px solid ${BORDER}`, padding: 16 }}>
              <div style={{ fontSize: 8, fontWeight: 700, color: "#64748b", textTransform: "uppercase",
                letterSpacing: 2, marginBottom: 8 }}>{sig.title}</div>
              <div style={{ fontWeight: 700, color: ACCENT, fontSize: 12 }}>{sig.name}</div>
              <div style={{ fontSize: 10, color: "#64748b", marginTop: 4 }}>{sig.role}</div>
              <div style={{ marginTop: 24, borderTop: `1px solid ${BORDER}`, paddingTop: 8,
                fontSize: 8, color: "#94a3b8" }}>Signature / Stamp</div>
            </div>
          ))}
        </div>

        {/* Forensic evidence registry — condensed exhibits summary */}
        <div style={{ marginTop: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
            letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
            Forensic Evidence Registry
          </div>
          <Table
            headers={["Exhibit", "Evidence Type", "Source", "Confidence", "Status"]}
            rows={[
              ["A", "Android Manifest Extraction", caseData.packageName || "Manifest", "99%", "VERIFIED"],
              ["B", "Permission Analysis Profile", `${permissions.length} permissions`, "97%", "VERIFIED"],
              ["C", "IOC Discovery Log", `${iocs.length} network indicators`, "94%", "VERIFIED"],
              ["D", "MITRE ATT&CK Mapping", `${mitreTags.length} techniques`, "91%", "VERIFIED"],
              ["E", "SHA-256 Binary Hash", (caseData.sha256 || "").slice(0, 24) + "…", "100%", "VERIFIED"],
            ]}
          />
        </div>

        <CalloutBox title="Digital Evidence Admissibility" color={GREEN}>
          All exhibits are hashed, timestamped, and blockchain-anchored under Case {cid}. Chain of custody
          maintained per CERT-In guidelines and IT Act 2000 Section 65B digital evidence standards.
        </CalloutBox>

        <PageFooter caseId={cid} />
      </Page>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* PAGE 15: APPENDIX                                                       */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <Page pageBreakAfter={false}>
        <PageHeader pageNum={15} section="Appendix" />
        <SectionTitle num="15" title="Appendix" />

        <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
          letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
          A. Complete Permission List
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 4, marginBottom: 24 }}>
          {permissions.map((p, i) => (
            <div key={i} style={{ padding: "4px 8px", fontSize: 8,
              fontFamily: "Courier New, monospace",
              background: highRiskPerms.includes(p) ? "#fef2f2" : STRIPE,
              border: `1px solid ${highRiskPerms.includes(p) ? "#fca5a5" : BORDER}`,
              color: highRiskPerms.includes(p) ? RED : "#475569" }}>
              {p.replace("android.permission.", "")}
            </div>
          ))}
        </div>

        <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
          letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 }}>
          B. Glossary
        </div>
        <Table
          headers={["Term", "Definition"]}
          rows={[
            ["APK",      "Android Package Kit — the file format used to distribute Android applications"],
            ["C2",       "Command and Control — remote server infrastructure used by malware operators"],
            ["IOC",      "Indicator of Compromise — forensic artefacts indicating a breach or malicious activity"],
            ["MITRE ATT&CK", "Adversarial Tactics, Techniques, and Common Knowledge — cybersecurity knowledge base"],
            ["OTP",      "One-Time Password — single-use authentication code used in banking"],
            ["TTPs",     "Tactics, Techniques, and Procedures — behavioural patterns of threat actors"],
            ["CERT-In",  "Computer Emergency Response Team India — national nodal agency for cybersecurity"],
            ["RBI",      "Reserve Bank of India — central banking institution overseeing financial security"],
          ]}
        />

        <div style={{ fontSize: 11, fontWeight: 700, color: ACCENT, textTransform: "uppercase",
          letterSpacing: 1, marginBottom: 10, borderBottom: `1px solid ${BORDER}`, paddingBottom: 6, marginTop: 16 }}>
          C. Legal Disclaimer
        </div>
        <p style={{ fontSize: 9, color: "#64748b", lineHeight: 1.6 }}>
          This report has been prepared by the BeaconTrap Automated Intelligence Platform for
          authorized recipients only. The information contained herein is classified CONFIDENTIAL
          and may not be reproduced, distributed, or shared without prior written consent.
          All analysis is based on static and heuristic examination of the submitted binary.
          BeaconTrap does not warrant the completeness or accuracy of dynamically evolving threat
          information. For incident response support, contact your designated SOC team immediately.
        </p>

        {/* Final branding bar */}
        <div style={{ marginTop: "auto", background: ACCENT, color: "#fff",
          padding: "12px 24px", margin: "auto -48px -36px",
          display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2 }}>BeaconTrap Intelligence Platform</span>
          <span style={{ fontSize: 9, color: "#94a3b8" }}>
            © {new Date().getFullYear()} · Case {cid} · Classification: CONFIDENTIAL
          </span>
        </div>
      </Page>

    </div>
  );
}
